### ISSUE TITLE
`run_neural_coin_dice.py` does not run on Google Collab

### ISSUE THREAD

**Issue by RichardWeissssssss** [google-research/dice_rl#28]
I have tried running the code from `run_neural_coin_dice.py` on [Google Collab](https://colab.research.google.com/drive/1IruKUtFG1OW1mJ8OxcEjiK9vT7wmN3jW?usp=sharing) (with a V100 GPU) and have encountered the following error:

```
FATAL Flags parsing error: Unknown command line flag 'f'
Pass --helpshort or --helpfull to see help on flags.
WARNING: Logging before flag parsing goes to stderr.
E0905 09:45:26.679535 133576772391552 ultratb.py:152] Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 156, in parse_flags_with_usage
    return FLAGS(args)
  File "/usr/local/lib/python3.10/dist-packages/absl/flags/_flagvalues.py", line 652, in __call__
    raise _exceptions.UnrecognizedFlagError(
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-243392e41e8e>", line 1, in <cell line: 1>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 300, in run
    args = _run_init(
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 369, in _run_init
    args = _register_and_parse_flags_with_usage(
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 216, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 166, in parse_flags_with_usage
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
UnrecognizedFlagError                     Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/absl/app.py in parse_flags_with_usage(args)
    155   try:
--> 156     return FLAGS(args)
    157   except flags.Error as error:

13 frames
/usr/local/lib/python3.10/dist-packages/absl/flags/_flagvalues.py in __call__(self, argv, known_only)
    651       suggestions = _helpers.get_flag_suggestions(name, list(self))
--> 652       raise _exceptions.UnrecognizedFlagError(
    653           name, value, suggestions=suggestions)

UnrecognizedFlagError: Unknown command line flag 'f'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-8-243392e41e8e> in <cell line: 1>()
----> 1 app.run(main)

/usr/local/lib/python3.10/dist-packages/absl/app.py in run(main, argv, flags_parser)
    299   try:
--> 300     args = _run_init(
    301         sys.argv if argv is None else argv,

/usr/local/lib/python3.10/dist-packages/absl/app.py in _run_init(argv, flags_parser)
    368   logging.use_absl_handler()
--> 369   args = _register_and_parse_flags_with_usage(
    370       argv=argv,

/usr/local/lib/python3.10/dist-packages/absl/app.py in _register_and_parse_flags_with_usage(argv, flags_parser)
    215   original_argv = sys.argv if argv is None else argv
--> 216   args_to_main = flags_parser(original_argv)
    217   if not FLAGS.is_parsed():

/usr/local/lib/python3.10/dist-packages/absl/app.py in parse_flags_with_usage(args)
    165     sys.stderr.write('Pass --helpshort or --helpfull to see help on flags.\n')
--> 166     sys.exit(1)
    167 

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2090                     stb = ['An exception has occurred, use %tb to see '
   2091                            'the full traceback.\n']
-> 2092                     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2093                                                                      value))
   2094                 else:

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    627             chained_exceptions_tb_offset = 0
    628             out_list = (
--> 629                 self.structured_traceback(
    630                     etype, evalue, (etb, chained_exc_ids),
    631                     chained_exceptions_tb_offset, context)

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1365         else:
   1366             self.tb = tb
-> 1367         return FormattedTB.structured_traceback(
   1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1265         if mode in self.verbose_modes:
   1266             # Verbose modes need a full traceback
-> 1267             return VerboseTB.structured_traceback(
   1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1122         """Return a nice text document describing the traceback."""
   1123 
-> 1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1125                                                                tb_offset)
   1126 

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

Maybe the code is only meant to be run locally?
My Computer is Windows (no Mujoco support) and does not have a GPU, so I tried an external solution.
I'd be glad if there was a quick fix :)

**Comment by MrWhiteRichard** [comment]
Ok never mind. With a good amount of adjustment-work I have now managed to run `run_neural_coin_dice.py` on my old Windows machine. If anyone is interested in how I did it, don't hesitate to contact me :)
